modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/MrUnknown404/SlabGen-Addon-BoP/issues"

[[mods]]
modId="slabgenbop"
version="1.0.0"
displayName="SlabGen Addon [BoP]"
displayURL="https://github.com/MrUnknown404/SlabGen-Addon-BoP"
#logoFile="examplemod.png"
credits=""
authors="-Unknown-"
description='''
Addon for SlabGen to add Biomes o' Plenty support
'''

[[dependencies.slabgenbop]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.slabgenbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.slabgenbop]]
    modId="slabgen"
    mandatory=true
    versionRange="[1.4.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.slabgenbop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.18.2-16.0.0.109,)"
    ordering="AFTER"
    side="BOTH"